spring:
  elasticsearch:
    rest:
      uris: localhost:9200
      username: test
      password: test
logging:
  level:
#    org.springframework.data.elasticsearch:
#      core: TRACE
#      client: TRACE
    #org.elasticsearch.client: TRACE
    org.apache.http: TRACE
    org.apache.http.wire: TRACE